### ISSUE TITLE
同样是select，通过什么来配置可以输入还是不可以输入呢？

### ISSUE THREAD

**Issue by x1234521** [cq-panda/Vue.NetCore#102]
同样是select，通过什么来配置可以输入还是不可以输入呢？
我通过E:\Vue.NetCore\Vol.Vue\src\views\appmanager\App_TransactionAvgPrice.vue来看，没看出来能输入与不不能输入的select控件有啥区别？

**Comment by cq-panda** [comment]
> 同样是select，通过什么来配置可以输入还是不可以输入呢？
> 我通过E:\Vue.NetCore\Vol.Vue\src\views\appmanager\App_TransactionAvgPrice.vue来看，没看出来能输入与不不能输入的select控件有啥区别？

下拉框选项超过10个就默认开启输入，这个输入只是过滤功能

**Comment by x1234521** [comment]
哦，原来如此，感谢~
