### ISSUE TITLE
VUE页面生成后台代码BUG。

### ISSUE THREAD

**Issue by x1234521** [cq-panda/Vue.NetCore#105]
E:\Vue.NetCore\Vue.Net\VOL.Builder\Services\Core\Partial\Sys_TableInfoService.cs
![image](https://user-images.githubusercontent.com/34298043/92438690-d6142e00-f1db-11ea-9dbd-5ec5ae173cec.png)

673行中x.SearchType == "checkbox"应该改为x.EditType == "checkbox"

**Comment by cq-panda** [comment]
> E:\Vue.NetCore\Vue.Net\VOL.Builder\Services\Core\Partial\Sys_TableInfoService.cs
> ![image](https://user-images.githubusercontent.com/34298043/92438690-d6142e00-f1db-11ea-9dbd-5ec5ae173cec.png)
> 
> 673行中x.SearchType == "checkbox"应该改为x.EditType == "checkbox"

感谢，周未与第二种查询布局一起更新

**Comment by x1234521** [comment]
收到，辛苦了~
