### ISSUE TITLE
js扩展里extension如何定义data(){}级别的变量？

### ISSUE THREAD

**Issue by x1234521** [cq-panda/Vue.NetCore#109]
希望定义完可以与VUE里的data(){}合并，供整个VUE内部使用。
不知道是否可以实现？

**Comment by cq-panda** [comment]
使用动态属性,onInit(){  this.xxx=1234 }
表单重置的好了？

**Comment by x1234521** [comment]
onInit(){}
searchBefore(param){}

我是想定义一个变量，在这2个方法内都可以使用。

**Comment by x1234521** [comment]
@cq-panda

**Comment by cq-panda** [comment]
onInit初始化好变量，其他地方都可以使用

**Comment by x1234521** [comment]
嗯，倒是可以用，，但，总感觉少了声明的过程，，虽然JS变量可以不声明直接用。
@cq-panda

**Comment by cq-panda** [comment]
> 嗯，倒是可以用，，但，总感觉少了声明的过程，，虽然JS变量可以不声明直接用。
> @cq-panda

并不是不声明，this.xx就是声明属性的过程

**Comment by x1234521** [comment]
嗯，好，按你的这个办法来。感谢，顺便问一下，菜单折叠功能有更新打算么？

**Comment by cq-panda** [comment]
> 嗯，好，按你的这个办法来。感谢，顺便问一下，菜单折叠功能有更新打算么？

在开发计划中，但这个可能还要等一段时间

**Comment by x1234521** [comment]
嗯嗯，辛苦了。
