### ISSUE TITLE
奇怪的显现？

### ISSUE THREAD

**Issue by x1234521** [cq-panda/Vue.NetCore#113]
快速查询和新建，这2个地方中的input，如果只有一个的时候，在输入框内回车，整个页面会回发刷新，，不知道什么原因，，多个input的时候就没问题，看了keypress事件，没找到相关代码，断点也无法断到，麻烦有空帮忙看下，谢谢了。

**Comment by cq-panda** [comment]
快速查询如果是input默认注册了一个回车查询事件，其他没有注册默认事件。可以看下是不是修改了代码或者自己注册了事件，再不行可以更新下basic下的组件

**Comment by x1234521** [comment]
不单是查询，新建也有这个问题，我查代码，没查到原因，你又空看看你的代码会不会有这个问题，只有一个input框的查询页和新建页都会有这个问题，，2个以上就没有这个问题。

我用你的最新代码搭建了一套，，一样存在这个问题，有空看看吧。

**Comment by x1234521** [comment]
![image](https://user-images.githubusercontent.com/34298043/97839956-27452780-1d1e-11eb-85d1-4c210ca571b9.png)

**Comment by cq-panda** [comment]
> 不单是查询，新建也有这个问题，我查代码，没查到原因，你又空看看你的代码会不会有这个问题，只有一个input框的查询页和新建页都会有这个问题，，2个以上就没有这个问题。
> 
> 我用你的最新代码搭建了一套，，一样存在这个问题，有空看看吧。

已修复

**Comment by x1234521** [comment]
原来这里的问题，感谢！
