### ISSUE TITLE
组件不够用

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [cq-panda/Vue.NetCore#115]
gridHeader、gridBody、gridFooter、modelHeader、modelBody、modelFooter 这几个组件不够用。

components: {//动态扩充组件或组件路径
        //表单header、content、footer对应位置扩充的组件
        gridHeader:()=>import("./Components/MasterDataHeaderExtend.vue"),//{ template: "<div>扩展组xx件</div>" },
        gridBody: ()=>import("./Components/MaterDataExtendModelBodyHeader.vue"),
        gridFooter: '',
        //弹出框(修改、编辑、查看)header、content、footer对应位置扩充的组件
        modelHeader: '',
        modelBody: '',
        modelFooter: '',
        calibrationReportHistory:()=>import("@/views/em/ct_em/EM_CalibrationReportHistory.vue")
    }
像这样增加的calibrationReportHistory，没有效果，打印this也没有calibrationReportHistory。

**Comment by cq-panda** [comment]
上面任意一个位置的vue里面，可以再添加N个子组件，不存在组件不够用的情况

**Comment by Dean-ZhenYao-Wang** [comment]
一个页面同时存在8个同级别的组件，不就不够用了

**Comment by cq-panda** [comment]
如果理解不了，可以把同级别的写在一个页面
