### ISSUE TITLE
能麻烦把权限相关的东西都理清了，然后更新下代码吗？

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [cq-panda/Vue.NetCore#119]
权限已经设置好了，但是还是提示没有权限操作

**Comment by Dean-ZhenYao-Wang** [comment]
![14e1746e1846c966dbd2e61e84522a33](https://user-images.githubusercontent.com/26154837/98650995-9f41cc00-2374-11eb-93f2-cf36a18163f7.jpg)
![4c1459dbc410275007055089543896ca](https://user-images.githubusercontent.com/26154837/98650999-a072f900-2374-11eb-9662-69f0be0a1389.jpg)
![3095f2ed64af25c4854272e27c682a87](https://user-images.githubusercontent.com/26154837/98651000-a10b8f80-2374-11eb-8f80-9f8c88481711.jpg)
![cedf12a68eafc0945cb463ba4a8673b0](https://user-images.githubusercontent.com/26154837/98651003-a1a42600-2374-11eb-8cbb-da34ac877d15.jpg)

**Comment by cq-panda** [comment]
sqlserver的菜单周未已经清理了。提示没有权限，可以查下sys_menu里表名是否重复了，或者调试ActionPermissionFilter.cs第99行位置的代码
