### ISSUE TITLE
大佬,下拉框数据绑定，可以动态传递参数吗,获取当前显示的表里的某个字段的值,根据这个值返回不同的下拉数据,显示不同的数据

### ISSUE THREAD

**Issue by lingyih** [cq-panda/Vue.NetCore#121]
下拉框数据绑定，可以动态传递参数吗,获取当前显示的表里的某个字段的值,根据这个值返回不同的下拉数据,显示不同的数据

**Comment by cq-panda** [comment]
![Uploading image.png…]()

**Comment by cq-panda** [comment]
modelOpenAfter (row) { //点击弹出框的时候从后台绑定数据源
        //可以判断当前是编辑还是新增
      if (this.currentAction == this.const.EDIT) {  
      }
      //row里面取值
      var url="url地址?params=参数名"//参数值从row里面取
      //从后台重新绑定数据源
      this.http.post(url, keys).then(result => {
        this.editFormOptions.forEach(x => {
          x.forEach(item => {
            //给指定字段重新绑定数据源
            if (item.field == "xxx") {
            //  result 格式 [{key:"1",value:"v1"},{key:"2",value:"v2"}]
              item.data = result
            }
          })
        })
      })
    },

**Comment by cq-panda** [comment]
<div style="color:#D4D4D4;background-color:#1E1E1E;font-family:Consolas, &quot;font-size:14px;line-height:19px;white-space:pre;">
	<div>
		&nbsp;<span style="color:#dcdcaa;">modelOpenAfter</span>&nbsp;(<span style="color:#9cdcfe;">row</span>)&nbsp;{&nbsp;<span style="color:#6a9955;">//点击弹出框的时候从后台绑定数据源</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//可以判断当前是编辑还是新增</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#c586c0;">if</span>&nbsp;(<span style="color:#569cd6;">this</span>.<span style="color:#9cdcfe;">currentAction</span>&nbsp;==&nbsp;<span style="color:#569cd6;">this</span>.<span style="color:#9cdcfe;">const</span>.<span style="color:#4fc1ff;">EDIT</span>)&nbsp;{&nbsp;&nbsp;
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//row里面取值</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">var</span>&nbsp;<span style="color:#9cdcfe;">url</span>=<span style="color:#ce9178;">"url地址?params=参数名"</span><span style="color:#6a9955;">//参数值从row里面取</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//从后台重新绑定数据源</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">this</span>.<span style="color:#9cdcfe;">http</span>.<span style="color:#dcdcaa;">post</span>(<span style="color:#9cdcfe;">url</span>,&nbsp;<span style="color:#9cdcfe;">keys</span>).<span style="color:#dcdcaa;">then</span>(<span style="color:#9cdcfe;">result</span>&nbsp;<span style="color:#569cd6;">=&gt;</span>&nbsp;{
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">this</span>.<span style="color:#9cdcfe;">editFormOptions</span>.<span style="color:#dcdcaa;">forEach</span>(<span style="color:#9cdcfe;">x</span>&nbsp;<span style="color:#569cd6;">=&gt;</span>&nbsp;{
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#9cdcfe;">x</span>.<span style="color:#dcdcaa;">forEach</span>(<span style="color:#9cdcfe;">item</span>&nbsp;<span style="color:#569cd6;">=&gt;</span>&nbsp;{
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//给指定字段重新绑定数据源</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#c586c0;">if</span>&nbsp;(<span style="color:#9cdcfe;">item</span>.<span style="color:#9cdcfe;">field</span>&nbsp;==&nbsp;<span style="color:#ce9178;">"xxx"</span>)&nbsp;{
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//&nbsp;&nbsp;result&nbsp;格式&nbsp;[{key:"1",value:"v1"},{key:"2",value:"v2"}]</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#9cdcfe;">item</span>.<span style="color:#9cdcfe;">data</span>&nbsp;=&nbsp;<span style="color:#9cdcfe;">result</span> 
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;},
	</div>
</div>

**Comment by lingyih** [comment]
页面table里面显示 的数据怎么动态获取值显示对应的数据值,存进数据库的是个编码,还需要在table页面上显示对应的汉字

**Comment by lingyih** [comment]
页面table里面显示 的数据怎么动态获取值显示对应的数据值,存进数据库的是个编码,还需要在table页面上显示对应的汉字

**Comment by lingyih** [comment]
viewgrid代码里没找到有渲染完成的直接触发的事件,已有的渲染时触发的事件都拿不到$refs.table.rowData,返回的都是空数组
![image](https://user-images.githubusercontent.com/35194956/99745804-cd61a180-2b14-11eb-8fa2-76717e8fab0d.png)
我把你文档里面给的事件都复制了,在每个里面都加了$refs.table.rowData,拿不到数据,只有在触发编辑,新建的事件里面能获取的值
![image](https://user-images.githubusercontent.com/35194956/99746636-07cb3e80-2b15-11eb-898d-1ffe8e799da0.png)

**Comment by cq-panda** [comment]
> $refs.table.rowData是后台异步返回的，你就算拿到组件渲染完成事件，也取不到这个data的值

**Comment by lingyih** [comment]
页面table里面显示 的数据怎么动态获取值显示对应的数据值,存进数据库的是个编码,还需要在table页面上显示对应的汉字   这个能解决吗

**Comment by cq-panda** [comment]
> 页面table里面显示 的数据怎么动态获取值显示对应的数据值,存进数据库的是个编码,还需要在table页面上显示对应的汉字 这个能解决吗

<div style="color:#D4D4D4;background-color:#1E1E1E;font-family:Consolas, &quot;font-size:14px;line-height:19px;white-space:pre;">
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#dcdcaa;">searchAfter</span>(<span style="color:#9cdcfe;">result</span>)&nbsp;{
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//获取返回的编码</span>
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">var</span>&nbsp;<span style="color:#9cdcfe;">arr</span>=&nbsp;<span style="color:#9cdcfe;">result</span>.<span style="color:#dcdcaa;">map</span>(<span style="color:#9cdcfe;">x</span><span style="color:#569cd6;">=&gt;</span>{&nbsp;<span style="color:#c586c0;">return</span>&nbsp;<span style="color:#9cdcfe;">x</span>.<span style="color:#9cdcfe;">编码字段</span>&nbsp;});
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">this</span>.<span style="color:#9cdcfe;">http</span>.<span style="color:#dcdcaa;">post</span>(<span style="color:#ce9178;">"url"</span>,<span style="color:#9cdcfe;">arr</span>).<span style="color:#dcdcaa;">then</span>(<span style="color:#9cdcfe;">source</span><span style="color:#569cd6;">=&gt;</span>{
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//根据返回的编号,重新绑定数据源(代码生成配置页面，给这个字段绑定一个数据源，可以选任意数据源)</span>
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#6a9955;">//soure格式[{key:"1",value:"va1"}]</span>
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#569cd6;">this</span>.<span style="color:#9cdcfe;">columns</span>.<span style="color:#dcdcaa;">find</span>(<span style="color:#9cdcfe;">x</span><span style="color:#569cd6;">=&gt;</span>{&nbsp;<span style="color:#9cdcfe;">x</span>.<span style="color:#9cdcfe;">field</span>==<span style="color:#ce9178;">"编码字段"</span>&nbsp;}).<span style="color:#9cdcfe;">data</span>=<span style="color:#9cdcfe;">source</span>;
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
	</div>
	<div>
		&nbsp;&nbsp;&nbsp;&nbsp;},
	</div>
</div>

**Comment by lingyih** [comment]
ok,谢谢

**Comment by lingyih** [comment]
![image](https://user-images.githubusercontent.com/35194956/99751769-d99e2c80-2b1d-11eb-800c-c3893f1cd2f0.png)
大佬,你发这个显示对应值的编码代码不太对吧,结构不太一样
![image](https://user-images.githubusercontent.com/35194956/99751862-123e0600-2b1e-11eb-9358-f44a142442f6.png)
按这个设置直接报错
![image](https://user-images.githubusercontent.com/35194956/99751900-284bc680-2b1e-11eb-9ea6-bab2b127a6af.png)
这样设置好像只是设置一个数据源吧,如果页面上每条数据的下拉数据源都不一样怎么办,后台返回的数据格式应该是每条数据对应的下拉数据吧.页面上有30条数据,返回30条数据的下拉数据

**Comment by cq-panda** [comment]
> this.columns.find(x=>{ x.field=="编码字段" }).data=source;

return漏了this.columns.find(x=>{return x.field=="编码字段" }).data=source;
这个只是table的code转换。编辑每个值的数据源不一样看下面发打开编辑框的处理

**Comment by lingyih** [comment]
![image](https://user-images.githubusercontent.com/35194956/99754610-b2e2f480-2b23-11eb-8677-6c3ee6358969.png)
你现在给我发的这个还是只是取到一个总值集,给这个字段绑定一个总的值,我这要效果是给这个表的每个行绑定一个不同的值,因为我这的值会根据表里的某个值去取不同的值,我无法确定这个值是否会出现相同的key,之类的,因为是不同地方传过来的,我这是个汇总,这个key有可能会出现重复,现在你给的这个如果出现相同的key,他只会显示第一个key的value.

**Comment by cq-panda** [comment]
前端开发28，后台开发23，或者用视图，都能解决你这种问题
