### ISSUE TITLE
查询界面的所有按钮无法动态隐藏或显示

### ISSUE THREAD

**Issue by slashXXxu** [cq-panda/Vue.NetCore#126]
查询界面的所有按钮无法动态隐藏或显示。

![Snipaste_2020-11-26_09-14-46](https://user-images.githubusercontent.com/33199494/100296826-2a9f9c00-2fc8-11eb-9fb2-78dcc0acf41c.png)

**Comment by cq-panda** [comment]
下次更新上

**Comment by slashXXxu** [comment]
2020-12-10实测版本可以用了。
