### ISSUE TITLE
建议增加多语言功能

### ISSUE THREAD

**Issue by zsinba** [cq-panda/Vue.NetCore#128]
建议增加多语言的支持；
建议增加不同数据库的支持；
建议增加自定义表单的支持；
建议增加不同数据库的支持；

算了，老板你看着选吧。框架嘛，就要支持常用的一些功能。

**Comment by cq-panda** [comment]
> 算了，老板你看着选吧。框架嘛，就要支持常用的一些功能。

这些功能都已经有了，多语言也有，只是没开放

**Comment by jessiondai** [comment]
> 
> 
> > 算了，老板你看着选吧。框架嘛，就要支持常用的一些功能。
> 
> 这些功能都已经有了，多语言也有，只是没开放

多语言能开放一下吗?
