### ISSUE TITLE
分辨率问题

### ISSUE THREAD

**Issue by KiisMyGun** [cq-panda/Vue.NetCore#148]
![image](https://user-images.githubusercontent.com/29726759/105675580-4a016980-5f24-11eb-848b-1ba13a59b41a.png)
由于分辨率的缩小导致。

![image](https://user-images.githubusercontent.com/29726759/105675533-3bb34d80-5f24-11eb-9f9e-a18c12c09705.png)

这个页面是扩展页面（gridBody），这个滚动条是页面主菜单栏的。由于分辨率的问题，滚动条现在显示到扩展页面了，影响到用户选择了。

**Comment by cq-panda** [comment]
> ![image](https://user-images.githubusercontent.com/29726759/105675580-4a016980-5f24-11eb-848b-1ba13a59b41a.png)
> 由于分辨率的缩小导致。
> 
> ![image](https://user-images.githubusercontent.com/29726759/105675533-3bb34d80-5f24-11eb-9f9e-a18c12c09705.png)
> 
> 这个页面是扩展页面（gridBody），这个滚动条是页面主菜单栏的。由于分辨率的问题，滚动条现在显示到扩展页面了，影响到用户选择了。

1、设置下按钮显示最大数量
2、以前修复过这个问题，可以更新下组件 或者自己调下样式
