### ISSUE TITLE
多数据表操作

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#15]
您好，

我要实现的业务会涉及到多张表的事务性操作，该怎么实现后台服务？ 如下写法貌似不正确，主要是服务怎样注入多个repository ？ 多谢 ！

![image](https://user-images.githubusercontent.com/506134/67619638-84b3b800-f830-11e9-91a0-2b274384205a.png)

**Comment by lvchaoin** [comment]
试了其它写法，有些写法不报错但是数据库没有写入，不知道啥情况，求指点
![image](https://user-images.githubusercontent.com/506134/67620648-bda55a00-f83b-11e9-8d24-41938dec82df.png)

**Comment by cq-panda** [comment]
第一个问题，你可以这样操作：
          repository.DbContextBeginTransaction(() =>
            {
                repository.Add(new App_Expert()
                {
                    City = ""
                });
                //其他表写法1
                repository.AddRange<test2019>(new List<test2019> { new test2019() { text = "111" } });
                //其他表写法2
                repository.DbContext.Set<test2019>().Add(new test2019() { text = "111" });
                //其他表写法3
                test2019Repository.Instance.Add(new test2019() { text = "111" },true);
                //上面添加参数true或下面SaverChanges提交数据
                repository.SaverChanges();
                //如果这里返回Error会回滚事务
                return new WebResponseContent().OK();
            });

第二个问题：
你使用的是Dapper的Add方法，方法里面还没实现所以不会写入数据库，下次更新会把Add方法实现

**Comment by lvchaoin** [comment]
多谢 ！
