### ISSUE TITLE
api返回数据序列化格式存在不统一情况

### ISSUE THREAD

**Issue by al1359** [cq-panda/Vue.NetCore#156]
1、在Startup.cs中配置了ContractResolver为CamelCasePropertyNamesContractResolver，WebAPI接口方法返回JsonResult类型时默认使用的是这个配置，所以返回的json是**首字母小写**；
2、在ConvertJsonExtension的Serialize方法中没配置，WebAPI接口方法返回ContentResult类型时大多调用了此方法，返回json**首字母大写** 。
在前端处理数据时就要特殊处理这两种情况，是否考虑改为统一方式更方便？

**Comment by cq-panda** [comment]
可以参照后台开发文档第三个  http://www.volcore.xyz/document/netCoreDev

**Comment by al1359** [comment]
好的，谢谢
