### ISSUE TITLE
绑定下拉框如何支持远程API或如何绑定大数据表

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#17]
不好意思，又来一个问题。

数据字典的方式绑定下拉框是个非常好用的特性。我的问题是，需要绑定的数据来自某个数据量比较大的表，怎样自动绑定是否能类似于根据数据的字符自动过滤或查询，设想应该是通过API的方式绑定？没有看到相关例子，请教下这个该如何实现

多谢 ！

**Comment by cq-panda** [comment]
数据字典长度现在好像是超过15个就默认开启了搜索功能，直接在select中输入字符过滤（如果不能搜索，获取下最新代码），这个也可以手动开启搜索功能。远程api搜索目前不支持。------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年10月29日(星期二) 晚上6:57
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 绑定下拉框如何支持远程API或如何绑定大数据表 (#17)



不好意思，又来一个问题。
 
数据字典的方式绑定下拉框是个非常好用的特性。我的问题是，需要绑定的数据来自某个数据量比较大的表，怎样自动绑定是否能类似于根据数据的字符自动过滤或查询，设想应该是通过API的方式绑定？没有看到相关例子，请教下这个该如何实现
 
多谢 ！
 
&mdash;
