### ISSUE TITLE
动态生成VolForm的数据不能双向绑定

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#173]
你好！咨询个问题，最近升级了下代码到最新版本，之前有个动态生成的VolForm，数据不能双向绑定，可能是啥原因？谢谢
代码结构如下：
1. 主页面通过modelBody引入子组件，modelBody: () => import('./LotTnxComponents/LotMove.vue'),
2. 在主页面中通过后台查询数据动态生成VolForm所需的Fields和Rules，通过$set方法将其传入子组件进行渲染（见图1），至此显示到页面都没有问题，包括按钮事件也都正常，但是数据不能双向绑定，始终为空（见图2），这个代码在大概一年前的版本运行是正常的，调试出来原因
   
![image](https://user-images.githubusercontent.com/506134/120928112-e7ac4700-c715-11eb-9623-c49991796bdc.png)

![image](https://user-images.githubusercontent.com/506134/120927872-f9d9b580-c714-11eb-9560-0926611cf7f2.png)

**Comment by cq-panda** [comment]
![image](https://user-images.githubusercontent.com/20450706/120929560-14fbf380-c71c-11eb-97b6-d96a2ef89e24.png)
这个字段由于以前拼写错误的问题，框架已经做过兼容处理，    
1、<VolForm :formFields="formCompleteFileds" :formRules="formCompleteRules" ></VolForm> 检查下:formFields是不是这样配置的拼写，如果是，在data属性中给formCompleteFileds初始化一个默认值：如：formCompleteFileds:{随便写:123}
2、如果<VolForm :formFileds=是这样写的，应该没有问题的。
3、如果还是不行，这个文件发来我看下
