### ISSUE TITLE
角色权限的获取

### ISSUE THREAD

**Issue by laosandegudai** [cq-panda/Vue.NetCore#175]
出现不同菜单对相同视图的不同权限控制时，下面方式获取会出现小权限集合出现大权现集合前面，导致权限出现异常。

![9061LI_4TYB`K@{GUQA}@3P](https://user-images.githubusercontent.com/17979159/124746949-06d80780-df54-11eb-8f3d-9320bd54603c.png)
![JI@V2Z_E3FH0J~Y~2RYT{OR](https://user-images.githubusercontent.com/17979159/124746969-0b9cbb80-df54-11eb-9bd8-9e8ff8ab9564.png)

**Comment by cq-panda** [comment]
框架默认禁止了一表多页面权限，下次我重新更新下脚本
