### ISSUE TITLE
主从表新增后点击保存是否可以自动变更为编辑状态

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#20]
您好，再咨询一个问题。

我在单表新增数据保存后，窗口会立即变更为编辑状态，然后再次点击保存按钮的时候实际上是更新数据。

在主从表的新增数据保存后，窗口会立即关闭，实际上我要扩展明细窗口的功能，希望它不要立即关闭，而是窗口继续停留便于进行后续操作，但是我希望它也像单表一样自动变更为编辑状态。

没找到从哪里修改，求教 ！！

感谢 ！
![image](https://user-images.githubusercontent.com/506134/67953147-8bc03900-fc29-11e9-84fe-2b7b5aad292c.png)

**Comment by cq-panda** [comment]
你希望主从表新建成功后，进入更新状态，不要关闭界面对吗 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 晚上9:58
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 主从表新增后点击保存是否可以自动变更为编辑状态 (#20)



您好，再咨询一个问题。
 
我在单表新增数据保存后，窗口会立即变更为编辑状态，然后再次点击保存按钮的时候实际上是更新数据。
 
在主从表的新增数据保存后，窗口会立即关闭，实际上我要扩展明细窗口的功能，希望它不要立即关闭，而是窗口继续停留便于进行后续操作，但是我希望它也像单表一样自动变更为编辑状态。
 
没找到从哪里修改，求教 ！！
 
感谢 ！
 
 
&mdash;

**Comment by lvchaoin** [comment]
是的，就是要这个

**Comment by cq-panda** [comment]
知道了，开发的时候故意让主从表新增后关闭的，明天上午我看下代码有没有留可以不关闭的属性，如果没有我添加一个 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 晚上10:06
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "保长"<283591387@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cq-panda/Vue.NetCore] 主从表新增后点击保存是否可以自动变更为编辑状态 (#20)



是的，就是要这个
 
&mdash;

**Comment by lvchaoin** [comment]
不关闭但是立即切换为编辑状态，也就是说页面应该能取到主表的主键值了，以及明细表的主键值是否应该也能取到了？ 因为如昨天咨询的，我的所有数据表都是以ID为主键，后台做了一点点修改来适应，不知道是否有影响，非常感谢！！

**Comment by cq-panda** [comment]
明天我看下后确认下，新增后变成编辑状态，主从表都能拿到主键，应该是没什么问题 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 晚上10:17
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "保长"<283591387@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cq-panda/Vue.NetCore] 主从表新增后点击保存是否可以自动变更为编辑状态 (#20)



不关闭但是立即切换为编辑状态，也就是说页面应该能取到主表的主键值了，以及明细表的主键值是否应该也能取到了？ 因为如昨天咨询的，我的所有数据表都是以ID为主键，后台做了一点点修改来适应，不知道是否有影响，非常感谢！！
 
&mdash;

**Comment by cq-panda** [comment]
现在可以通过属性设置新建或编辑成功后是否关闭弹出框：
![image](https://user-images.githubusercontent.com/20450706/67997842-e3de5600-fc90-11e9-823a-91c3df7eff58.png)

**Comment by cq-panda** [comment]
> 现在可以通过属性设置新建或编辑成功后是否关闭弹出框，需要获取下最新代码：
> ![image](https://user-images.githubusercontent.com/20450706/67997842-e3de5600-fc90-11e9-823a-91c3df7eff58.png)

**Comment by lvchaoin** [comment]
可以了，非常感谢 ！
