### ISSUE TITLE
Method.js编辑窗口为只读，仍需要扩展按钮，功能会存在于扩展组件中

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#21]
场景为单表进入编辑，但是编辑内容全设置为只读。因为会引入modelBody组件来实现业务功能，此时
希望扩展按钮到弹出框，做如下代码修改可以达成，如果合理请并入。。

![image](https://user-images.githubusercontent.com/506134/68083433-8fd79b00-fe63-11e9-9606-3eeead71a988.png)

![image](https://user-images.githubusercontent.com/506134/68083538-ad593480-fe64-11e9-80c7-d746f3ff53a6.png)

**Comment by cq-panda** [comment]
> 希望扩展按钮到弹出框，做如下代码修改可以达成，如果合理请并入。。

感谢建议，刚在demo扩展js中增加了描述，因考虑是没有编辑与新建权限的都不需要扩展按钮操作，如果只是某些页面没有编辑与新建权限也需要添加扩展按钮，建议在onInited方法中操作 this.boxButtons.push(...)

**Comment by lvchaoin** [comment]
多谢 ！
