### ISSUE TITLE
为菜单增加额外的权限

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#22]
再一个请教，确实需要为某个菜单增加额外的权限，但是保存的时候会提示验证无法通过。请问下该功能是否还没有实现？另外当增加了新的权限后，前后台（后台应该是在controller标注）分别在什么位置去做控制？

感谢 ！

![image](https://user-images.githubusercontent.com/506134/68100531-68d0a600-ff03-11e9-8f8d-cd4673996b72.png)

**Comment by cq-panda** [comment]
> 再一个请教，确实需要为某个菜单增加额外的权限，但是保存的时候会提示验证无法通过。请问下该功能是否还没有实现？另外当增加了新的权限后，前后台（后台应该是在controller标注）分别在什么位置去做控制？
> 
> 感谢 ！
> 
> ![image](https://user-images.githubusercontent.com/506134/68100531-68d0a600-ff03-11e9-8f8d-cd4673996b72.png)

![image](https://user-images.githubusercontent.com/20450706/68100791-f4970200-ff04-11e9-940c-db82f2216b64.png)
你看下这个，每个partial控制器中都添加了权限标识说明

**Comment by lvchaoin** [comment]
这个问问题之前看过，就是我问题里面说的后台是通过在controller的anotation里面做到的控制，增加权限就多加一个枚举值。
现在遇到的问题是前台如何增加额外的权限（实际只是个别页面），保存的时候会报错（提示数据验证不通过！），另外增加额外的权限后怎么控制不同的人可以看到不同的功能按钮，所以需求主要是前端部分的控制。

多谢！

**Comment by cq-panda** [comment]
> 这个问问题之前看过，就是我问题里面说的后台是通过在controller的anotation里面做到的控制，增加权限就多加一个枚举值。
> 现在遇到的问题是前台如何增加额外的权限（实际只是个别页面），保存的时候会报错（提示数据验证不通过！），另外增加额外的权限后怎么控制不同的人可以看到不同的功能按钮，所以需求主要是前端部分的控制。
> 
> 多谢！

1、保存的时候会报错（提示数据验证不通过！）?
    是提示的权限还是实体验证没通过?
2、另外增加额外的权限后怎么控制不同的人可以看到不同的功能按钮
  * 你在onInited使用 this.$store.getters.getUserInfo();拿到用户信息来区分不同用户(这个里没有用户名，如果需要用户名，在首页返回用户的信息中添加字段)，如果需要用户权限使用： this.$store.state.system.permission获取。
  *  或者可以更具体点，你可以遍历botton数组，设置hidden/disabled属性决定是否显示/是否可用按钮，  onInited查询界面添加按钮使用 this.boxButtons.push(...按钮配置)，弹出框架界面使用this.detailOptions.buttons.push(...按钮配置)
![image](https://user-images.githubusercontent.com/20450706/68101516-ed71f300-ff08-11e9-86b2-533a8a0924df.png)

**Comment by lvchaoin** [comment]
感谢 ！

1. 就是在菜单管理中增加其他权限，点击确认按钮，然后就如下面这样，这个在demo站点测试的
2. 关于按钮的可见/不可见，在前台能否增加一个directive，譬如就叫v-can=true/false, 这样碰到有这样属性的按钮，就会自动去确认按钮自己的权限，然后设置可见性。

![image](https://user-images.githubusercontent.com/506134/68101756-38403a80-ff0a-11e9-9129-e2b67343600c.png)

**Comment by cq-panda** [comment]
> 感谢 ！
> 
> 1. 就是在菜单管理中增加其他权限，点击确认按钮，然后就如下面这样，这个在demo站点测试的
> 2. 关于按钮的可见/不可见，在前台能否增加一个directive，譬如就叫v-can=true/false, 这样碰到有这样属性的按钮，就会自动去确认按钮自己的权限，然后设置可见性。
> 
> ![image](https://user-images.githubusercontent.com/506134/68101756-38403a80-ff0a-11e9-9129-e2b67343600c.png)

1、因为上次修改过弹出框组件的默认大小，而没修改菜单页面弹出框的大小，权限名称下面还有一列，你把往下滚动一点就可以看到了，你拉取下代码,菜单页面弹出框的大小已经补上了
2、就会自动去确认按钮自己的权限，然后设置可见性？没太理解你说的这个，现在权限的自动确认，都是根据后台返回的权限页面加载时再判断前端的权限是否显示。
3、在前台能否增加一个directive，譬如就叫v-can=true/false？。我的理解这个就是和现在hidden属性是一样的

**Comment by lvchaoin** [comment]
ok，了解了，就是没看到权限值这个输入框，导致对实现有一些猜测，以为还要通过遍历或者其它代码来控制，看到权限代码那个输入框我就明白了。
多谢！

**Comment by cq-panda** [comment]
> ok，了解了，就是没看到权限值这个输入框，导致对实现有一些猜测，以为还要通过遍历或者其它代码来控制，看到权限代码那个输入框我就明白了。
> 多谢！

代码都是与生产上项目的通用功能一起在维护，中间有些在测试时存在遗漏的问题。
