### ISSUE TITLE
表单动态生成情况下字段验证规则不生效

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#25]
您好，咨询下如下问题

我的表单字段是在modelOpenBefore里动态生成的，modelBody放了一个VolForm，如果表单字段是预先在data中写好的，那么验证的rules都会生效，如果是在方法里动态生成的，验证规则就不生效，如下图，验证规则都是正确的，不允许为空的字段前面就没有星号，怎么解？多谢！
![image](https://user-images.githubusercontent.com/506134/68202551-ed541f00-fffe-11e9-99fa-a59b76643903.png)

**Comment by cq-panda** [comment]
modebody的组建是独立的，这个不应该有问题的，明天确认下------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月5日(星期二) 晚上7:04
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 表单动态生成情况下字段验证规则不生效 (#25)



您好，咨询下如下问题
 
我的表单字段是在modelOpenBefore里动态生成的，modelBody放了一个VolForm，如果表单字段是预先在data中写好的，那么验证的rules都会生效，如果是在方法里动态生成的，验证规则就不生效，如下图，验证规则都是正确的，不允许为空的字段前面就没有星号，怎么解？多谢！
 
 
&mdash;

**Comment by cq-panda** [comment]
你说的这个没星号，我感觉你是动态做了数组的属性修改，如果是这样的话，你用$set来修改------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月5日(星期二) 晚上7:04
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 表单动态生成情况下字段验证规则不生效 (#25)



您好，咨询下如下问题
 
我的表单字段是在modelOpenBefore里动态生成的，modelBody放了一个VolForm，如果表单字段是预先在data中写好的，那么验证的rules都会生效，如果是在方法里动态生成的，验证规则就不生效，如下图，验证规则都是正确的，不允许为空的字段前面就没有星号，怎么解？多谢！
 
 
&mdash;

**Comment by lvchaoin** [comment]
还是无效，用$set后字段也能正常显示，验证依然无效

![image](https://user-images.githubusercontent.com/506134/68208923-42972d00-000d-11ea-9d96-d2bb39f58505.png)

![image](https://user-images.githubusercontent.com/506134/68208994-665a7300-000d-11ea-8427-6a3cebabf5d2.png)

**Comment by cq-panda** [comment]
动态添加删除带验证规则的表单已重写，你获取下就行了

**Comment by lvchaoin** [comment]
测试好使，日期类型不能选择，非常感谢！ 学习一下，关键问题是？

**Comment by cq-panda** [comment]
> 测试好使，日期类型不能选择，非常感谢！ 学习一下，关键问题是？

没理解你说的日期类型不能选择是什么意思？能否截个图或详细一点，另外刚刚提交的更新有点多，主要是编辑表单样式优化与demo，你可全部获取下

**Comment by lvchaoin** [comment]
当动态表单有datetime类型时，打开会有如下报错
![image](https://user-images.githubusercontent.com/506134/68292321-93b72780-00c6-11ea-9ec6-964059d4b3f1.png)

**Comment by cq-panda** [comment]
看到了，明天我抽时间改下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lvchaoin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 晚上6:53
收件人:&nbsp;"cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com&gt;;
抄送:&nbsp;"283591387"<283591387@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cq-panda/Vue.NetCore] 表单动态生成情况下字段验证规则不生效 (#25)




当动态表单有datetime类型时，打开会有如下报错

**Comment by lvchaoin** [comment]
已解决，是针对日期的rule需要指定type属性，我没有指定。另外请教下这个之前验证不生效主要的原因是什么，没来得及研究新改的代码，学习一下，多谢！！
