### ISSUE TITLE
上传文件包含的列在数据字典中定义为查询语句

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#26]
数据字典中定义为查询语句时上传excel会有问题，做了如下修改，你看看怎么改

```
private static List<CellOptions> GetExportColumnInfo(string tableName, bool temlate = false, bool filterKeyValue = true)
        {
            //&& x.IsDisplay == 1&&x.IsReadDataset==0只导出代码生器中设置为显示并且不是只读的列，可根据具体业务设置导出列
            List<CellOptions> cellOptions = DBServerProvider.DbContext.Set<Sys_TableColumn>()
              .Where(x => x.TableName == tableName && x.IsDisplay == 1 && x.IsReadDataset == 0).Select(c => new CellOptions()
              {
                  ColumnName = c.ColumnName,
                  ColumnCNName = c.ColumnCnName,
                  DropNo = c.DropNo,
                  Requierd = c.IsNull > 0 ? false : true,
                  ColumnWidth = c.ColumnWidth ?? 90
              }).ToList();

            if (temlate) return cellOptions;

            var dicNos = cellOptions.Where(x => !string.IsNullOrEmpty(x.DropNo)).Select(c => c.DropNo);

            if (dicNos.Count() == 0) return cellOptions;

            List<Sys_Dictionary> dictionaries = DictionaryManager.GetDictionaries(dicNos);
            //获取绑定字典数据源下拉框的值
            foreach (string dicNo in dicNos.Distinct())
            {
                Dictionary<string, string> keyValues = null;

                if (dictionaries.Find(p => p.DicNo == dicNo).DbSql != string.Empty)//通过查询语句
                {
                    var data = DBServerProvider.SqlDapper.QueryList<KeyValueDto>(dictionaries
                        .Find(p => p.DicNo == dicNo).DbSql, null).ToList();
                    if (filterKeyValue)
                    {
                        keyValues = data
                            .Where(w => w.key != w.value)? //key==value相同的则不处理
                            .ToDictionary(r => r.key, r => r.value);
                    }
                    else
                    {
                        keyValues = data.ToDictionary(r => r.key, r => r.value);
                    }
                }
                else//通过数据字典
                {
                    var query = dictionaries
                       .Where(x => x.DicNo == dicNo && x.Sys_DictionaryList != null)
                       .Select(s => s.Sys_DictionaryList);
                    //   .FirstOrDefault()
                    //.Where(w => (filterKeyValue && w.DicName != w.DicValue)|| !filterKeyValue) //key==value相同的则不处理
                    //   .ToDictionary(r => r.DicValue, r => r.DicName);
                    if (filterKeyValue)
                    {
                        keyValues = query.FirstOrDefault()?
                         .Where(w => w.DicName != w.DicValue)? //key==value相同的则不处理
                          .ToDictionary(r => r.DicValue, r => r.DicName);
                    }
                    else
                    {
                        keyValues = query.FirstOrDefault()?.ToDictionary(r => r.DicValue, r => r.DicName);
                    }
                }
                foreach (CellOptions options in cellOptions.Where(x => x.DropNo == dicNo))
                {
                    options.KeyValues = keyValues;
                }
            }
            return cellOptions;
        }
    }

  public class KeyValueDto
    {
        public string key { get; set; }
        public string value { get; set; }
    }

```

**Comment by cq-panda** [comment]
> 数据字典中定义为查询语句时上传excel会有问题，做了如下修改，你看看怎么改
> 
> ```
> private static List<CellOptions> GetExportColumnInfo(string tableName, bool temlate = false, bool filterKeyValue = true)
>         {
>             //&& x.IsDisplay == 1&&x.IsReadDataset==0只导出代码生器中设置为显示并且不是只读的列，可根据具体业务设置导出列
>             List<CellOptions> cellOptions = DBServerProvider.DbContext.Set<Sys_TableColumn>()
>               .Where(x => x.TableName == tableName && x.IsDisplay == 1 && x.IsReadDataset == 0).Select(c => new CellOptions()
>               {
>                   ColumnName = c.ColumnName,
>                   ColumnCNName = c.ColumnCnName,
>                   DropNo = c.DropNo,
>                   Requierd = c.IsNull > 0 ? false : true,
>                   ColumnWidth = c.ColumnWidth ?? 90
>               }).ToList();
> 
>             if (temlate) return cellOptions;
> 
>             var dicNos = cellOptions.Where(x => !string.IsNullOrEmpty(x.DropNo)).Select(c => c.DropNo);
> 
>             if (dicNos.Count() == 0) return cellOptions;
> 
>             List<Sys_Dictionary> dictionaries = DictionaryManager.GetDictionaries(dicNos);
>             //获取绑定字典数据源下拉框的值
>             foreach (string dicNo in dicNos.Distinct())
>             {
>                 Dictionary<string, string> keyValues = null;
> 
>                 if (dictionaries.Find(p => p.DicNo == dicNo).DbSql != string.Empty)//通过查询语句
>                 {
>                     var data = DBServerProvider.SqlDapper.QueryList<KeyValueDto>(dictionaries
>                         .Find(p => p.DicNo == dicNo).DbSql, null).ToList();
>                     if (filterKeyValue)
>                     {
>                         keyValues = data
>                             .Where(w => w.key != w.value)? //key==value相同的则不处理
>                             .ToDictionary(r => r.key, r => r.value);
>                     }
>                     else
>                     {
>                         keyValues = data.ToDictionary(r => r.key, r => r.value);
>                     }
>                 }
>                 else//通过数据字典
>                 {
>                     var query = dictionaries
>                        .Where(x => x.DicNo == dicNo && x.Sys_DictionaryList != null)
>                        .Select(s => s.Sys_DictionaryList);
>                     //   .FirstOrDefault()
>                     //.Where(w => (filterKeyValue && w.DicName != w.DicValue)|| !filterKeyValue) //key==value相同的则不处理
>                     //   .ToDictionary(r => r.DicValue, r => r.DicName);
>                     if (filterKeyValue)
>                     {
>                         keyValues = query.FirstOrDefault()?
>                          .Where(w => w.DicName != w.DicValue)? //key==value相同的则不处理
>                           .ToDictionary(r => r.DicValue, r => r.DicName);
>                     }
>                     else
>                     {
>                         keyValues = query.FirstOrDefault()?.ToDictionary(r => r.DicValue, r => r.DicName);
>                     }
>                 }
>                 foreach (CellOptions options in cellOptions.Where(x => x.DropNo == dicNo))
>                 {
>                     options.KeyValues = keyValues;
>                 }
>             }
>             return cellOptions;
>         }
>     }
> 
>   public class KeyValueDto
>     {
>         public string key { get; set; }
>         public string value { get; set; }
>     }
> ```

你的理解是对的，这个导入时自定义sql校验数据源我们目前还没实际用到所以功能一直没处理，因为还要考虑其他一些细节，没有按你的方式写，你获取下，另外能否把你动态修改表单组件添加的datetime类型这个代码截图下，我这里测试没有发现异常

**Comment by lvchaoin** [comment]
多谢！
