### ISSUE TITLE
VolForm可否增加一个prop可设置label-width

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#27]
当前默认值为100，有时需要稍微宽一点，多谢！

**Comment by cq-panda** [comment]
可以，现在整理文档，要等文档一起更新了，如果少数情况需要增加标签宽度，可以写css控制------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月9日(星期六) 晚上11:16
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] VolForm可否增加一个prop可设置label-width (#27)



当前默认值为100，有时需要稍微宽一点，多谢！
 
&mdash;

**Comment by lvchaoin** [comment]
谢谢，这个宽度渲染到页面上就直接到style里去了，没搞明白怎么覆盖，写css好像不好使

**Comment by cq-panda** [comment]
目前手上新加的东西不少，那我尽量周一单独更新下这个，可以用样式穿透覆盖style的属性 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月9日(星期六) 晚上11:36
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "保长"<283591387@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cq-panda/Vue.NetCore] VolForm可否增加一个prop可设置label-width (#27)



谢谢，这个宽度渲染到页面上就直接到style里去了，没搞明白怎么覆盖，写css好像不好使
 
&mdash;

**Comment by lvchaoin** [comment]
另外，volbox里的这句会导致在IE（ie11）弹出框不居中，靠右边显示了，去掉这句即可

![image](https://user-images.githubusercontent.com/506134/68537959-dcf9c680-03a7-11ea-8bf2-f0fcfeee450f.png)

**Comment by cq-panda** [comment]
好的，谢谢，周一提交





------------------ 原始邮件 ------------------
发件人: lvchaoin <notifications@github.com&gt;
发送时间: 2019年11月10日 10:51
收件人: cq-panda/Vue.NetCore <Vue.NetCore@noreply.github.com&gt;
抄送: 保长 <283591387@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[cq-panda/Vue.NetCore] VolForm可否增加一个prop可设置label-width (#27)




另外，volbox里的这句会导致在IE（ie11）弹出框不居中，靠右边显示了，去掉这句即可

**Comment by cq-panda** [comment]
自定义表单select数据源值为数字验证不通过、IE弹出框不居中的问题已处理
自定义表单标签宽度：
![image](https://user-images.githubusercontent.com/20450706/68563960-3508f980-048a-11ea-88bb-a540effccb23.png)
如果需要设置代码生成页面的label宽度，在onInit中处理
如果单独使用的Form表单使用属性设置 ：  <VolForm :label-width='170'>

**Comment by lvchaoin** [comment]
多谢！
