### ISSUE TITLE
form绑定数据源key值为数值型，且设置select为required时验证无法通过

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#28]
如下，datakey绑定的数据源Materials中key值为数值型（数据库的ID字段），前台的select选中了值但是依然提示要选取， 绑定中的key更改为字符型就没有问题了，多谢！

![image](https://user-images.githubusercontent.com/506134/68543737-2ffa6a80-03f6-11ea-97ac-1096b0a6dcdc.png)

![image](https://user-images.githubusercontent.com/506134/68543741-37ba0f00-03f6-11ea-8695-1951b414a94b.png)

**Comment by cq-panda** [comment]
这个目前就是这样的，key只能设置成字符串类型，后面更新会改进这个问题 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月10日(星期天) 晚上8:14
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] form绑定数据源key值为数值型，且设置select为required时验证无法通过 (#28)



如下，datakey绑定的数据源Materials中key值为数值型（数据库的ID字段），前台的select选中了值但是依然提示要选取， 绑定中的key更改为字符型就没有问题了，多谢！
 

 

 
&mdash;

**Comment by lvchaoin** [comment]
好的，多谢，我这边改下绑定目前也能满足需要。另外咨询下，如下我的form中三个select是con从上到下需要联动的，在每一个select的onchange里写事件重新绑定数据源？或者有其他方法？多谢 ！

![image](https://user-images.githubusercontent.com/506134/68544095-72be4180-03fa-11ea-86a4-0966b69be4a7.png)

**Comment by cq-panda** [comment]
目前只能自己通过onchang绑定，里面有onchang方法，你可以在bind里添加一个属性来缓存数据------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月10日(星期天) 晚上8:43
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "保长"<283591387@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cq-panda/Vue.NetCore] form绑定数据源key值为数值型，且设置select为required时验证无法通过 (#28)



好的，多谢，我这边改下绑定目前也能满足需要。另外咨询下，如下我的form中三个select是con从上到下需要联动的，在每一个select的onchange里写事&#x4EF6;重新绑定数据源？或者有其他方法？多谢 ！
 

 
&mdash;

**Comment by lvchaoin** [comment]
谢谢 ！

**Comment by mymastermvc** [comment]
"DbConnectionString": "Data Source=MYMSSQLSERVER;Initial Catalog=netcoredev;Persist Security Info=True;User ID=sa;Password=sec069;Connect Timeout=500;",
我的資料庫名稱MYMSSQLSERVER請問這樣寫對嗎
