### ISSUE TITLE
可以把ef2.1换成dapper吗？

### ISSUE THREAD

**Issue by 107295472** [cq-panda/Vue.NetCore#3]
ef感觉灵活，很笨

**Comment by cq-panda** [comment]
EF只是用来做简单查询、修改的，如果觉得EF不好用，可以直接用EF执行sql语句。框架也内置了dapper的封装，框架后台代码里提供了9种数据库调用方试，Demo里有介绍，你可以看看后台扩展代码SellOrderService.cs类里的介绍
