### ISSUE TITLE
控制绑定数据列的显示颜色及查询框的回车事件

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#30]
您好，咨询两个问题，
1. 数据列表中的绑定列都生成为tag，颜色貌似自动产生的，如果希望按照tag值（绑定数据值）来设定颜色，应该在哪里里修改？
2. 多数页面的searchform第一个都是input输入框，希望这里可以设置回车事件来执行查询按钮的功能，这样譬如用扫描枪扫描后就自动查询了，怎样才能实现？

多谢 ！

![image](https://user-images.githubusercontent.com/506134/68765583-1193a980-0658-11ea-8f2e-293ab30dcfd7.png)

![image](https://user-images.githubusercontent.com/506134/68765715-66cfbb00-0658-11ea-86ae-c64684c59eda.png)

**Comment by cq-panda** [comment]
这两个功能我抽空给你加，到时候加完了我告诉你

**Comment by cq-panda** [comment]
多数页面的searchform第一个都是input输入框，已添加在input标签中输入值后按回车进行查询
数据列表中的绑定列都生成为tag，颜色貌似自动产生的，在onInit方法中实现:

![image](https://user-images.githubusercontent.com/20450706/68869667-863c1600-0734-11ea-86ff-53d46fa86f83.png)
![image](https://user-images.githubusercontent.com/20450706/68869692-8dfbba80-0734-11ea-9e9e-fbec8f016213.png)

最近基础组件优化了很多组件与新增了大量demo,在演示环境能看到，获取时可能会存在冲突

**Comment by lvchaoin** [comment]
多谢！
