### ISSUE TITLE
可以为空的数字验证

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#32]
请教下是否可以实现数字验证非必须输入（输个0也可以，但是对用户不友好），我尝试了自定义验证，但是貌似有些问题，无法返回（见下面第图三），我的输入框全部为动态生成。

另加一个问题，在这个页面如果有很多input，可以在input输入按enter键后自动切换到下一个么，tab键可以但是不方便，用jquery也许能达成目的，看看你这有没有更方便的方式。

感谢 ！

![image](https://user-images.githubusercontent.com/506134/68952104-40498580-07fa-11ea-9b63-fdef39af64ce.png)
![image](https://user-images.githubusercontent.com/506134/68952734-5dcb1f00-07fb-11ea-8771-7b515f546b85.png)
![image](https://user-images.githubusercontent.com/506134/68952797-7dfade00-07fb-11ea-987b-da7b65f7494b.png)

**Comment by lvchaoin** [comment]
自定义验证我会搞了（改成如下即可），帮忙建议下enter切换输入框的问题，多谢！

**Comment by cq-panda** [comment]
1、你获取下最新代码，数字input必填的标签，如果为空时，默认给了个0
2、自定表单无法返回，是没有callback的，直接返回字符串就行了，
3、【框架文档】里已经提交了一些组件的文档(在本地能看到)，在【组件api】中（表单的文档写完了,已经废弃了columnType属性，如果定义了也是能使用）
4、在input输入按enter键后自动切换到下一个，这个问题，可能你们的业务跟我们做的有区别，这个我再想想，如果添加了我再告诉你

**Comment by cq-panda** [comment]
你获取下，通过 $event 去找下一个input标签或手动触发tab键应该能解决你的问题

     {
            title: "手机号",
            required: true, 
            field: "myPhone",
            type: "phone",
            onKeyPress: $event => {
              if ($event.keyCode == 13) {
              }
            }
         }

**Comment by lvchaoin** [comment]
多谢！ 研究了一下，模拟tab键貌似不容易，ie可以，其它浏览器可能有安全问题的障碍，最后是通过寻找下一个input的方式，但是对volform做了一点点修改方便查找input对象，应该不影响框架，你看是否更新进去
所有的input都加一个ref如下
![image](https://user-images.githubusercontent.com/506134/68994554-2d4cb900-08bf-11ea-9d3f-9f7f58492997.png)
然后我的查找代码会是这样
![image](https://user-images.githubusercontent.com/506134/68994565-4b1a1e00-08bf-11ea-9d07-e760a0a69afe.png)
