### ISSUE TITLE
PGSQL 查询异常

### ISSUE THREAD

**Issue by yuzhupeng** [cq-panda/Vue.NetCore#325]
服务器处理出现异常:42703: 字段 s.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在
服务器处理出现异常:42703: 字段 s0.ColumnCnName 不存在

**Comment by SikroYang** [comment]
请问后来怎么解决的？
