### ISSUE TITLE
后台可以支持一个主表，多个子表新增编辑删除吗？具体代码怎么实现呢

### ISSUE THREAD

**Issue by tianyang1027** [cq-panda/Vue.NetCore#331]

**Comment by xiazhaozhao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by thkings** [comment]
企业版有此功能

**Comment by tianyang1027** [comment]
> 企业版有此功能

现在这个版本只支持一个主表，一个子表，操作吗？

**Comment by thkings** [comment]
是的

**Comment by cq-panda** [comment]
参照一对多的示例，手动配置下多个子表

**Comment by tianyang1027** [comment]
> 参照一对多的示例，手动配置下多个子表

![image](https://github.com/cq-panda/Vue.NetCore/assets/7963894/4fdcf3ff-d1c6-49e2-91a9-483551b5527f)
这样吗
