### ISSUE TITLE
全局的时间格式配置不生效

### ISSUE THREAD

**Issue by tianyang1027** [cq-panda/Vue.NetCore#336]
![image](https://github.com/cq-panda/Vue.NetCore/assets/7963894/d77373ca-92f2-4206-acfc-163671ae313f)
![image](https://github.com/cq-panda/Vue.NetCore/assets/7963894/c557d680-6af9-4027-8cd9-bd578e29fdb5)

**Comment by cq-panda** [comment]
修改服务器日期格式

**Comment by tianyang1027** [comment]
果然，改了服务器时间格式，已生效，多谢
