### ISSUE TITLE
Searchform无法展开在IE11

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#34]
今天测到IE11浏览器，查询按钮右边的downarrow按钮正常点击后应该展开searchform的内容，但是在IE11下点击向下箭头后就直接触发了查询事件，无法展开form，多谢！

![image](https://user-images.githubusercontent.com/506134/69009191-0a3d0a80-098e-11ea-8bb4-27ff495c1f99.png)

**Comment by lvchaoin** [comment]
实际上是icon添加的事件没生效，网上有如下解决方案，但是我这边改了都没用
![image](https://user-images.githubusercontent.com/506134/69016919-f4573600-09dd-11ea-8738-6a06ccbfeafc.png)

**Comment by cq-panda** [comment]
我一会改下这个 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月18日(星期一) 上午8:32
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [cq-panda/Vue.NetCore] Searchform无法展开在IE11 (#34)



实际上是icon添加的事&#x4EF6;没生效，网上有如下解决方案，但是我这边改了都没用
 
 
&mdash;

**Comment by cq-panda** [comment]
已修复

**Comment by lvchaoin** [comment]
感谢，已测！
