### ISSUE TITLE
这是多租户吗？

### ISSUE THREAD

**Issue by SikroYang** [cq-panda/Vue.NetCore#346]
这哪叫多租户啊，本来冲着多租户来的，吭哧吭哧写了两天表结构，一看没TenantId字段，我还以为我漏了，结果就是用户隔离，多租户不应该是多组织架构隔离吗？

**Comment by xiazhaozhao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cq-panda** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
