### ISSUE TITLE
Voltable自定义查询条件不生效

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#37]
后台也是自定义的api，查询条件格式也是自定义，在loadbefore中修改param，跟踪到voltable的load方法里，发现最后http调用的api带的参数并没有改变，另外这个业务需求我并不需要分页，voltable是否能满足？ 多谢！

![image](https://user-images.githubusercontent.com/506134/69245031-1240b880-0be1-11ea-819b-33adb2def812.png)

voltable组件此处未看到查询参数变化
![image](https://user-images.githubusercontent.com/506134/69245103-2b496980-0be1-11ea-9adc-ef1c5bc089fd.png)

自定义的api参数需求如下
![image](https://user-images.githubusercontent.com/506134/69245145-3dc3a300-0be1-11ea-8935-ffad1d8caa00.png)

**Comment by cq-panda** [comment]
table的文档明天会更新上去，第一个问题我确认一下，第二个是可以不用分页的，明天我看下代码后再回复------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月20日(星期三) 晚上10:01
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] Voltable自定义查询条件不生效 (#37)



后台也是自定义的api，查询条&#x4EF6;格式也是自定义，在loadbefore中修改param，跟踪到voltable的load方法里，发现最后http调用的api带的参数并没有改变，另外这个业务需求我并不需要分页，voltable是否能满足？ 多谢！
 

 
voltable组&#x4EF6;此处未看到查询参数变化
 
 
自定义的api参数需求如下
 
 
&mdash;

**Comment by cq-panda** [comment]
第一个问题你不能param=｛｝这样操作对象，这样操作相当于把param参数在内存中指向了另外一个地址，你使用param.xxx添加新的参数就可以了，另外对于不想分页的我明天过滤下多余的分页参数 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月20日(星期三) 晚上10:01
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] Voltable自定义查询条件不生效 (#37)



后台也是自定义的api，查询条&#x4EF6;格式也是自定义，在loadbefore中修改param，跟踪到voltable的load方法里，发现最后http调用的api带的参数并没有改变，另外这个业务需求我并不需要分页，voltable是否能满足？ 多谢！
 

 
voltable组&#x4EF6;此处未看到查询参数变化
 
 
自定义的api参数需求如下
 
 
&mdash;

**Comment by cq-panda** [comment]
第二个问题：  设置 :pagination-hide="true"属性即可不使用分页

**Comment by lvchaoin** [comment]
可以了，多谢！
