### ISSUE TITLE
删除的数据记录包含其它表的外键值后台没有抛出异常

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#40]
这里的代码在执行executenonquery里实际是有异常的，但是整个方法执行完提示的是成功，没有抛出错误信息

![image](https://user-images.githubusercontent.com/506134/69489278-31289e80-0eb0-11ea-8dc6-c96de7a091aa.png)

**Comment by cq-panda** [comment]
![image](https://user-images.githubusercontent.com/20450706/69489469-291e2e00-0eb3-11ea-92d9-13fbd5b793f4.png)
已添加接收返回对象，通过statushuo获取到返回状态，异常的话message存的异常信息

**Comment by lvchaoin** [comment]
多谢！

这里还有一个好像之前是不是改过，就是上传的时候如果绑定的是sql数据源，keyvalues应该从sql里面取，现在好像又不可以了？

![image](https://user-images.githubusercontent.com/506134/69490100-cb431380-0ebd-11ea-96d5-decb9729f523.png)

**Comment by cq-panda** [comment]
这个你上次提了就加上了，你那边现在要是不能从sql中获取，麻烦把你配置的sql发我看下，我确认下 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2019年11月24日(星期天) 下午2:12
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "保长"<283591387@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cq-panda/Vue.NetCore] 删除的数据记录包含其它表的外键值后台没有抛出异常 (#40)



多谢！
 
这里还有一个好像之前是不是改过，就是上传的时候如果绑定的是sql数据源，keyvalues应该从sql里面取，现在好像又不可以了？
 

 
&mdash;

**Comment by lvchaoin** [comment]
图没上去，EPPlusHelper.cs

![image](https://user-images.githubusercontent.com/506134/69490535-88d10500-0ec4-11ea-8c22-31c064ccdb34.png)
