### ISSUE TITLE
SqlDapper 能否完善一下

### ISSUE THREAD

**Issue by MITVIP** [cq-panda/Vue.NetCore#42]
Vue.NetCore/Vue.Net/VOL.Core/Dapper/SqlDapper.cs
增加,修改,删除方法都直接return true;没有具体实现

**Comment by cq-panda** [comment]
文档发布后，会抽时间完善这个 ------------------ 原始邮件 ------------------
发件人: "MITVIP"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 中午11:49
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] SqlDapper 能否完善一下 (#42)



Vue.NetCore/Vue.Net/VOL.Core/Dapper/SqlDapper.cs
 增加,修改,删除方法都直接return true;没有具体实现
 
&mdash;
