### ISSUE TITLE
发现问题两个问题：1.数据库不是主键的guid类型的生成模型的类型是guid，2.当起别名时，删除方法报错

### ISSUE THREAD

**Issue by Devin-hjc** [cq-panda/Vue.NetCore#43]
1.数据库不是主键的guid类型的生成模型的类型是guid（报错，应该是Guid），原因见下图1
2.当起别名时，删除方法报错：对象名“xxx”无效，原因见图2
![image](https://user-images.githubusercontent.com/33113941/69775366-7e1fb400-11d3-11ea-97c7-3ebbc4a135b2.png)

![image](https://user-images.githubusercontent.com/33113941/69775283-3d279f80-11d3-11ea-97c8-c0e7d0197de5.png)

感谢开源，这个项目很棒，点赞

**Comment by Devin-hjc** [comment]
还有，像删除方法那样，是不是会有sql注入的问题呢

**Comment by cq-panda** [comment]
非常感谢！
问题1，2你获取下代码就行了。
问题3：目录只支持自增ID与GUID作为主键，删除时这行代码就是对数据类型校验,   IEnumerable<(bool, string, object)> validation = keyProperty.ValidationValueForDbType(keys);

**Comment by Devin-hjc** [comment]
感谢，哈哈还有两个问题
1.同步表结构时，也会有上面“别名”的问题
2.如果我想在每一行（固定列）添加一个自定义方法的按钮（如 删除等），能实现吗

**Comment by cq-panda** [comment]
第一个问题，我确认下
第二个问题,可以在前端表对应的扩展js中找到methods属性添加一个onInit方法即可实现，可参考文档组件api【代码生成后页面viewGrid】(文档还没写完)，具体Demo扩展文件src\views\document\docApi\doc_viewGrid\doc_viewGirdExtension.js

![image](https://user-images.githubusercontent.com/20450706/69841288-8c380800-1299-11ea-8b76-ba1423c4143d.png)

**Comment by Devin-hjc** [comment]
了解，谢谢

**Comment by cq-panda** [comment]
onInit方法中操作this.columns，你可以干你自己任何想干的事

**Comment by Devin-hjc** [comment]
赞👍，棒
