### ISSUE TITLE
运行项目后点击使用到了组件VolForm的路由，在 src目录下的 components -> basic -> VolForm.vue下的Select报错（maxTagCount）

### ISSUE THREAD

**Issue by SuperficialL** [cq-panda/Vue.NetCore#5]
```js
Invalid prop: type check failed for prop "maxTagCount". Expected Number with value 2, got String with value "2"
```
> 看了IView官网的[事例](https://www.iviewui.com/components/select#BQJH)，[api](https://www.iviewui.com/components/select#API)后发现 Select 中的属性`max-tag-count`为`number`类型，其用到了绑定的写法
```js
// 错误写法
max-tag-count="2"
// 正确写法
:max-tag-count="2"
```

**Comment by cq-panda** [comment]
多谢指正，目前iview使用的是3.2.2版本，max-tag-count在3.4.0及以后的版本才能使用， VolForm.vue已移除max-tag-count属性，后续看实际情况再添加
