### ISSUE TITLE
下拉绑定数据量大时性能问题

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#55]
使用过程中碰到下拉绑定的原始表数据量大，譬如物料清单表，导致页面加载所有数据有性能问题，看了下前后台都要改，可能要采用remote search方式再加个top N应该能解决，有空帮忙看看该怎么下手，多谢！

**Comment by cq-panda** [comment]
这个我想想 ------------------ 原始邮件 ------------------
发件人: "lvchaoin"<notifications@github.com>
发送时间: 2020年1月3日(星期五) 晚上11:26
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 下拉绑定数据量大时性能问题 (#55)



使用过程中碰到下拉绑定的原始表数据量大，譬如物料清单表，导致页面加载所有数据有性能问题，看了下前后台都要改，可能要采用remote search方式再加个top N应该能解决，有空帮忙看看该怎么下手，多谢！
 
&mdash;

**Comment by cq-panda** [comment]
表单select远程搜索已添加
1、在onInit中通过this.editFormOptions找到需要远程搜索的这段，设置remote=true即可从后台字典模糊查询数据源(只支持数据字典配置的自定义sql)。如需要从指定接口中查询。设置url='api/xx/xx'

如果数据量比较多时，设置的remote=true，请在数据字典配置的自定义sql，将sql取top

**Comment by lvchaoin** [comment]
非常感谢，已测试okay。
