### ISSUE TITLE
是否有考虑增加AD域认证登陆登陆模块

### ISSUE THREAD

**Issue by BenetteLee** [cq-panda/Vue.NetCore#77]
首先感谢大佬的成品框架。
顺路问一句是否有考虑增加AD域认证的登陆方式呢？

**Comment by cq-panda** [comment]
框架只提供基础功能，其他功能根据自己需要修改框架添加就行------------------ 原始邮件 ------------------
发件人: "BenetteLee"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 上午9:02
收件人: "cq-panda/Vue.NetCore"<Vue.NetCore@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Vue.NetCore] 是否有考虑增加AD域认证登陆登陆模块 (#77)




 
首先感谢大佬的成品框架。
 顺路问一句是否有考虑增加AD域认证的登陆方式呢？
 
&mdash;

**Comment by BenetteLee** [comment]
好的，感谢回复！
