### ISSUE TITLE
和APP交互，这个项目怎么使用

### ISSUE THREAD

**Issue by anxiaolei** [cq-panda/Vue.NetCore#89]
咱这个项目只是针对后台管理的，如果编写和APP交互的API，是需要再重新建一个API项目吗，还是有别的方法？求大神支招

**Comment by cq-panda** [comment]
> 咱这个项目只是针对后台管理的，如果编写和APP交互的API，是需要再重新建一个API项目吗，还是有别的方法？求大神支招

建议再建一个api项目，然后把现有的所有webapi配置及startup等复制过去。再添加一个与BaseController类似的基础控制器。其他不变

**Comment by anxiaolei** [comment]
👍
