### ISSUE TITLE
部署到linux 下图片验证码问题。

### ISSUE THREAD

**Issue by wangjiec1** [cq-panda/Vue.NetCore#93]
我把项目部署在centOS7 上api   getVierificationCode
获取不到数据。查了一下需要 libgdiplus。请问，你们是怎么解决这个问题的。

**Comment by wangjiec1** [comment]
安装libgdiplus的命令
yum install libgdiplus-devel

**Comment by cq-panda** [comment]
> 安装libgdiplus的命令
> yum install libgdiplus-devel

centos上我是两年前的装了，具体是哪些忘了

**Comment by zsyinglive** [comment]
感谢，遇到同样的问题了，虽然还在解决中，但至少提供了个思路
