### ISSUE TITLE
VolForm Validate问题

### ISSUE THREAD

**Issue by lvchaoin** [cq-panda/Vue.NetCore#95]
如下方法应该还是有问题，可能因为foreach里面的field.validate方法本身是异步执行的，下面的语句实际会先于各字段的validate返回结果，最后会导致Result始终是True。暂时把下面部分的语句包了个settimeout在使用，没找到正确解决办法，多谢！

![2020-07-18_180108](https://user-images.githubusercontent.com/506134/87850234-419af700-c921-11ea-91dc-f9fe07bf01f1.png)
![2020-07-18_175437](https://user-images.githubusercontent.com/506134/87850237-4364ba80-c921-11ea-9336-5c7049b9010f.png)

**Comment by cq-panda** [comment]
> 如下方法应该还是有问题，可能因为foreach里面的field.validate方法本身是异步执行的，下面的语句实际会先于各字段的validate返回结果，最后会导致Result始终是True。暂时把下面部分的语句包了个settimeout在使用，没找到正确解决办法，多谢！
> 
> ![2020-07-18_180108](https://user-images.githubusercontent.com/506134/87850234-419af700-c921-11ea-91dc-f9fe07bf01f1.png)
> ![2020-07-18_175437](https://user-images.githubusercontent.com/506134/87850237-4364ba80-c921-11ea-9336-5c7049b9010f.png) 感谢，看了下源码，是异步执行的，已经回滚，获取下使用回调进行同步处理就可以了
